name: Deploy website on push

on:
  push:
    branches:
      - main
      - main-2
  pull_request:
    branches:
      - main
      - main-2

jobs:
  deploy-main:
    name: Deploy to sat.mpiric.us
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files to sat.mpiric.us
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.mpiric.us
          username: sat@sat.mpiric.us
          password: "${{ secrets.FTP_PASS }}"
          server-dir: /

  deploy-main-2:
    name: Deploy to newdomain.com
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main-2'
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files to newdomain.com
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 184.107.141.21  # Replace with actual FTP server
          username: cbepl@cbepl.com  # Replace with actual FTP username
          password: "${{ secrets.NEW_FTP_PASS }}"  # Store this in GitHub Secrets
          server-dir: /
